name: Biome Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  biome-update:
    name: Update Biome version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.0

      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 'lts/*'

      - name: Biome version update
        run: npx --yes @biomejs/biome migrate --write

      - name: Biome format
        run: npx --yes @biomejs/biome format daily-schedule-card.js --write

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.9
        id: pr
        with:
          token: ${{ secrets.BIOME_GITHUB_TOKEN }}
          branch: create-pull-request/biome-update
          title: Biome update
          body: Automated changes by "biome-update" GitHub action
          commit-message: Biome update

      - name: Enable auto-merge
        if: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge --auto --merge ${{ steps.pr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
